[package]
name = "in-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
aj = { version = "=0.7.0-a.1", path = "../../aj" }
serde = { version = "1.0.64", features = ["derive"] }
actix-rt = "2.2"
chrono = { version = "0.4.34" }
