[package]
name = "aj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
redis = "0.23.0"
cron = "0.12.0"
actix = "0.13.0"
serde = { version = "1.0.64", features = ["derive"] }
serde_json = "1.0.64"
uuid = { version = "0.8", features = ["serde", "v4"] }
log = "0.4"
lazy_static = { version = "1.4.0", features = [] }
