[package]
name = "tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.40.0", features = ["full"] }
aj = { version = "=0.7.1", path = "../../aj" }
serde = { version = "1.0.64", features = ["derive"] }
